### PR TITLE
Fix 429 again

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by SolarDrew** [comment]
Does this change actually do anything? It's not clear to me that the new code isn't equivalent to the old code

**Comment by SolarDrew** [comment]
Ah of course. I should really drink more coffee before I review code...

In that case LGTM unless want to condense it as suggested, @Cadair.

**Comment by Cadair** [comment]
You can't index the thing inside the await. I think you would either need an extra set of () or this.

**Comment by jacobtomlinson** [comment]
Ah yes it would be

**Pull request merged**
